packages:
  - examples/**

catalogs:
  dev:
    "@luxass/eslint-config": ^5.0.0
    "@luxass/utils": ^2.3.0
    "@nuxt/kit": ^3.17.5
    "@nuxt/schema": ^3.17.5
    "@rspack/core": ^1.3.15
    "@types/node": ^22.9.0
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
    esbuild: ^0.25.5
    eslint: ^9.29.0
    publint: ^0.3.12
    rolldown: 1.0.0-beta.19
    rollup: ^4.44.0
    tsdown: ^0.12.8
    typescript: ^5.8.3
    vite: ^6.3.5
    vitest: ^3.2.4
    vitest-testdirs: ^4.0.1
    webpack: ^5.99.9

  example:
    "@astrojs/check": ^0.9.4
    "@nuxtjs/tailwindcss": ^6.14.0
    "@rspack/cli": 1.3.15
    "@tailwindcss/vite": ^4.1.10
    "@vitejs/plugin-react": ^4.5.2
    "@vitejs/plugin-vue": ^5.2.4
    astro: ^5.10.0
    autoprefixer: ^10.4.21
    next: 15.3.4
    nuxt: ^3.17.5
    postcss: ^8.5.6
    postcss-loader: ^8.1.1
    react: ^19.1.0
    react-dom: ^19.1.0
    react-router-dom: ^7.6.2
    shiki: ^3.7.0
    tailwindcss: ^4.1.10
    ts-node: ^10.9.2
    unplugin-vue-router: ^0.12.0
    vite-plugin-inspect: ^11.2.0
    vite-plugin-vue-devtools: ^7.7.7
    vue: ^3.5.17
    vue-loader: ^17.4.2
    vue-router: ^4.5.1
    vue-tsc: ^2.2.10

  prod:
    "@rollup/pluginutils": ^5.2.0
    unplugin: ^2.3.5
    yaml: ^2.8.0

onlyBuiltDependencies:
  - esbuild
