packages:
  - examples/**

catalogs:
  dev:
    "@luxass/eslint-config": ^4.18.1
    "@nuxt/kit": ^3.17.2
    "@nuxt/schema": ^3.17.2
    "@rspack/core": ^1.3.9
    "@types/node": ^22.9.0
    "@types/react": ^19.1.3
    "@types/react-dom": ^19.1.3
    esbuild: ^0.25.4
    eslint: ^9.26.0
    publint: ^0.3.12
    rolldown: 1.0.0-beta.9
    rollup: ^4.40.2
    tsdown: ^0.12.0
    typescript: ^5.8.3
    vite: ^6.3.5
    vitest: ^3.1.3
    vitest-testdirs: ^4.0.0
    webpack: ^5.99.8

  example:
    "@astrojs/check": ^0.9.4
    "@nuxtjs/tailwindcss": ^6.14.0
    "@rspack/cli": 1.3.11
    "@tailwindcss/vite": ^4.1.6
    "@vitejs/plugin-react": ^4.4.1
    "@vitejs/plugin-vue": ^5.2.4
    astro: ^5.7.12
    autoprefixer: ^10.4.21
    next: 15.3.2
    nuxt: ^3.17.2
    postcss: ^8.5.3
    postcss-loader: ^8.1.1
    react: ^19.1.0
    react-dom: ^19.1.0
    react-router-dom: ^7.6.0
    shiki: ^3.4.0
    tailwindcss: ^4.1.6
    ts-node: ^10.9.2
    unplugin-vue-router: ^0.12.0
    vite-plugin-inspect: ^11.0.1
    vite-plugin-vue-devtools: ^7.7.6
    vue: ^3.5.13
    vue-loader: ^17.4.2
    vue-router: ^4.5.1
    vue-tsc: ^2.2.10

  prod:
    "@rollup/pluginutils": ^5.1.4
    unplugin: ^2.3.2
    yaml: ^2.7.1

onlyBuiltDependencies:
  - esbuild
