packages:
  - examples/**

catalogs:
  dev:
    "@luxass/eslint-config": 6.0.3
    "@luxass/utils": 2.7.2
    "@nuxt/kit": 4.3.0
    "@nuxt/schema": 4.3.0
    "@rspack/core": 1.7.3
    "@types/node": 22.19.7
    "@types/react": 19.2.9
    "@types/react-dom": 19.2.3
    esbuild: 0.27.2
    eslint: 9.38.0
    publint: 0.3.17
    rolldown: 1.0.0-rc.1
    rollup: 4.56.0
    tsdown: 0.20.1
    typescript: 5.9.3
    vite: 7.1.12
    vitest: 4.0.4
    vitest-testdirs: 4.3.0
    webpack: 5.104.1

  example:
    "@astrojs/check": 0.9.6
    "@nuxtjs/tailwindcss": 6.14.0
    "@rspack/cli": 1.7.3
    "@tailwindcss/vite": 4.1.18
    "@vitejs/plugin-react": 5.1.0
    "@vitejs/plugin-vue": 6.0.1
    astro: 5.16.15
    autoprefixer: 10.4.23
    next: 16.1.5
    nuxt: 4.3.0
    postcss: 8.5.6
    postcss-loader: 8.2.0
    react: 19.2.3
    react-dom: 19.2.3
    react-router-dom: 7.13.0
    shiki: 3.21.0
    tailwindcss: 4.1.18
    ts-node: 10.9.2
    unplugin-vue-router: 0.19.2
    vite-plugin-inspect: 11.3.3
    vite-plugin-vue-devtools: 8.0.3
    vue: 3.5.27
    vue-loader: 17.4.2
    vue-router: 4.6.4
    vue-tsc: 3.2.4

  prod:
    "@rollup/pluginutils": 5.3.0
    unplugin: 2.3.11
    yaml: 2.8.2

onlyBuiltDependencies:
  - esbuild
