packages:
  - examples/**

catalogs:
  dev:
    "@luxass/eslint-config": ^4.18.1
    "@luxass/utils": ^2.2.1
    "@nuxt/kit": ^3.17.4
    "@nuxt/schema": ^3.17.4
    "@rspack/core": ^1.3.12
    "@types/node": ^22.9.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
    esbuild: ^0.25.5
    eslint: ^9.27.0
    publint: ^0.3.12
    rolldown: 1.0.0-beta.10
    rollup: ^4.41.1
    tsdown: ^0.12.4
    typescript: ^5.8.3
    vite: ^6.3.5
    vitest: ^3.1.4
    vitest-testdirs: ^4.0.0
    webpack: ^5.99.9

  example:
    "@astrojs/check": ^0.9.4
    "@nuxtjs/tailwindcss": ^6.14.0
    "@rspack/cli": 1.3.13
    "@tailwindcss/vite": ^4.1.8
    "@vitejs/plugin-react": ^4.5.0
    "@vitejs/plugin-vue": ^5.2.4
    astro: ^5.8.0
    autoprefixer: ^10.4.21
    next: 15.3.3
    nuxt: ^3.17.4
    postcss: ^8.5.3
    postcss-loader: ^8.1.1
    react: ^19.1.0
    react-dom: ^19.1.0
    react-router-dom: ^7.6.1
    shiki: ^3.4.2
    tailwindcss: ^4.1.8
    ts-node: ^10.9.2
    unplugin-vue-router: ^0.12.0
    vite-plugin-inspect: ^11.1.0
    vite-plugin-vue-devtools: ^7.7.6
    vue: ^3.5.15
    vue-loader: ^17.4.2
    vue-router: ^4.5.1
    vue-tsc: ^2.2.10

  prod:
    "@rollup/pluginutils": ^5.1.4
    unplugin: ^2.3.5
    yaml: ^2.8.0

onlyBuiltDependencies:
  - esbuild
