packages:
  - examples/**
catalog:
  "@astrojs/check": ^0.9.4
  "@luxass/eslint-config": ^4.15.0
  "@tailwindcss/vite": ^4.0.8
  "@nuxt/kit": ^3.15.4
  "@nuxt/schema": ^3.15.4
  "@nuxtjs/tailwindcss": ^6.13.1
  "@rollup/pluginutils": ^5.1.4
  "@rspack/cli": 1.2.7
  "@rspack/core": ^1.2.5
  "@types/node": ^22.9.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@vitejs/plugin-react": ^4.3.4
  "@vitejs/plugin-vue": ^5.2.1
  astro: ^5.3.0
  autoprefixer: ^10.4.20
  esbuild: ^0.25.0
  eslint: ^9.21.0
  next: 15.2.1
  nuxt: ^3.15.4
  postcss: ^8.5.3
  postcss-loader: ^8.1.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router-dom: ^7.2.0
  rolldown: 1.0.0-beta.3
  rollup: ^4.34.8
  shiki: ^3.0.0
  tailwindcss: ^4.0.8
  ts-node: ^10.9.2
  tsup: ^8.3.6
  typescript: ^5.7.3
  unplugin: ^2.2.0
  unplugin-vue-router: ^0.12.0
  vite: ^6.1.1
  vite-plugin-inspect: ^10.2.1
  vite-plugin-vue-devtools: ^7.7.2
  vitest: ^3.0.6
  vitest-testdirs: ^2.1.1
  vue: ^3.5.13
  vue-loader: ^17.4.2
  vue-router: ^4.5.0
  vue-tsc: ^2.2.2
  webpack: ^5.98.0
  yaml: ^2.7.0
