packages:
  - examples/**
catalog:
  "@astrojs/check": ^0.9.4
  "@luxass/eslint-config": ^4.15.0
  "@tailwindcss/vite": ^4.0.1
  "@nuxt/kit": ^3.15.4
  "@nuxt/schema": ^3.15.4
  "@nuxtjs/tailwindcss": ^6.13.1
  "@rollup/pluginutils": ^5.1.4
  "@rspack/cli": 1.2.2
  "@rspack/core": ^1.2.2
  "@types/node": ^22.9.0
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  "@vitejs/plugin-react": ^4.3.4
  "@vitejs/plugin-vue": ^5.2.1
  astro: ^5.2.1
  autoprefixer: ^10.4.20
  esbuild: ^0.24.2
  eslint: ^9.19.0
  next: 15.1.6
  nuxt: ^3.15.4
  postcss: ^8.5.1
  postcss-loader: ^8.1.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router-dom: ^7.1.4
  rolldown: 1.0.0-beta.3
  rollup: ^4.32.1
  shiki: ^2.2.0
  tailwindcss: ^4.0.1
  ts-node: ^10.9.2
  tsup: ^8.3.6
  typescript: ^5.7.3
  unplugin: ^2.1.2
  unplugin-vue-router: ^0.11.2
  vite: ^6.0.11
  vite-plugin-inspect: ^10.1.0
  vite-plugin-vue-devtools: ^7.7.1
  vitest: ^3.0.4
  vitest-testdirs: ^2.1.1
  vue: ^3.5.13
  vue-loader: ^17.4.2
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
  webpack: ^5.97.1
  yaml: ^2.7.0
