packages:
  - examples/**
catalog:
  "@astrojs/check": ^0.9.4
  "@luxass/eslint-config": ^4.16.0
  "@tailwindcss/vite": ^4.0.14
  "@nuxt/kit": ^3.16.0
  "@nuxt/schema": ^3.16.0
  "@nuxtjs/tailwindcss": ^6.13.2
  "@rollup/pluginutils": ^5.1.4
  "@rspack/cli": 1.2.8
  "@rspack/core": ^1.2.8
  "@types/node": ^22.9.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@vitejs/plugin-react": ^4.3.4
  "@vitejs/plugin-vue": ^5.2.1
  astro: ^5.5.2
  autoprefixer: ^10.4.21
  esbuild: ^0.25.1
  eslint: ^9.22.0
  next: 15.2.3
  nuxt: ^3.16.0
  postcss: ^8.5.3
  postcss-loader: ^8.1.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router-dom: ^7.3.0
  rolldown: 1.0.0-beta.4
  rollup: ^4.35.0
  shiki: ^3.2.1
  tailwindcss: ^4.0.14
  ts-node: ^10.9.2
  tsup: ^8.4.0
  typescript: ^5.8.2
  unplugin: ^2.2.0
  unplugin-vue-router: ^0.12.0
  vite: ^6.2.1
  vite-plugin-inspect: ^11.0.0
  vite-plugin-vue-devtools: ^7.7.2
  vitest: ^3.0.8
  vitest-testdirs: ^2.1.1
  vue: ^3.5.13
  vue-loader: ^17.4.2
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  webpack: ^5.98.0
  yaml: ^2.7.0
onlyBuiltDependencies:
  - esbuild
