packages:
  - examples/**

catalogs:
  dev:
    "@luxass/eslint-config": ^5.1.1
    "@luxass/utils": ^2.6.0
    "@nuxt/kit": ^3.17.7
    "@nuxt/schema": ^3.17.7
    "@rspack/core": ^1.4.7
    "@types/node": ^22.9.0
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
    esbuild: ^0.25.6
    eslint: ^9.31.0
    publint: ^0.3.12
    rolldown: 1.0.0-beta.27
    rollup: ^4.45.0
    tsdown: ^0.12.9
    typescript: ^5.8.3
    vite: ^7.0.4
    vitest: ^3.2.4
    vitest-testdirs: ^4.0.1
    webpack: ^5.100.1

  example:
    "@astrojs/check": ^0.9.4
    "@nuxtjs/tailwindcss": ^6.14.0
    "@rspack/cli": 1.4.7
    "@tailwindcss/vite": ^4.1.11
    "@vitejs/plugin-react": ^4.6.0
    "@vitejs/plugin-vue": ^6.0.0
    astro: ^5.11.1
    autoprefixer: ^10.4.21
    next: 15.4.1
    nuxt: ^3.17.7
    postcss: ^8.5.6
    postcss-loader: ^8.1.1
    react: ^19.1.0
    react-dom: ^19.1.0
    react-router-dom: ^7.6.3
    shiki: ^3.8.0
    tailwindcss: ^4.1.11
    ts-node: ^10.9.2
    unplugin-vue-router: ^0.14.0
    vite-plugin-inspect: ^11.3.0
    vite-plugin-vue-devtools: ^7.7.7
    vue: ^3.5.17
    vue-loader: ^17.4.2
    vue-router: ^4.5.1
    vue-tsc: ^3.0.1

  prod:
    "@rollup/pluginutils": ^5.2.0
    unplugin: ^2.3.5
    yaml: ^2.8.0

onlyBuiltDependencies:
  - esbuild
