packages:
  - examples/**

catalogs:
  dev:
    "@luxass/eslint-config": ^4.17.1
    "@nuxt/kit": ^3.16.1
    "@nuxt/schema": ^3.16.1
    "@rspack/core": ^1.3.0
    "@types/node": ^22.9.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4
    esbuild: ^0.25.1
    eslint: ^9.23.0
    publint: ^0.3.12
    rolldown: 1.0.0-beta.7
    rollup: ^4.38.0
    tsdown: ^0.11.3
    typescript: ^5.8.2
    vite: ^6.2.3
    vitest: ^3.0.9
    vitest-testdirs: ^2.2.0
    webpack: ^5.98.0

  example:
    "@astrojs/check": ^0.9.4
    "@nuxtjs/tailwindcss": ^6.13.2
    "@rspack/cli": 1.3.0
    "@tailwindcss/vite": ^4.0.17
    "@vitejs/plugin-react": ^4.3.4
    "@vitejs/plugin-vue": ^5.2.3
    astro: ^5.5.5
    autoprefixer: ^10.4.21
    next: 15.2.4
    nuxt: ^3.16.1
    postcss: ^8.5.3
    postcss-loader: ^8.1.1
    react: ^19.1.0
    react-dom: ^19.1.0
    react-router-dom: ^7.4.1
    shiki: ^3.2.1
    tailwindcss: ^4.0.17
    ts-node: ^10.9.2
    unplugin-vue-router: ^0.12.0
    vite-plugin-inspect: ^11.0.0
    vite-plugin-vue-devtools: ^7.7.2
    vue: ^3.5.13
    vue-loader: ^17.4.2
    vue-router: ^4.5.0
    vue-tsc: ^2.2.8

  prod:
    "@rollup/pluginutils": ^5.1.4
    unplugin: ^2.2.2
    yaml: ^2.7.1

onlyBuiltDependencies:
  - esbuild
