name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
    uses: luxass/shared-workflows/.github/workflows/reusable-ci.yaml@b55f08ac1aca5a4a3ae198bd8a7197c0157b3ef7 # v0.10.0
    with:
      build-script: "build"
      lint-script: "lint"
      fmt: true
      fmt-script: "fmt:check"
      typecheck-script: "typecheck"

  test:
    permissions:
      contents: read
    strategy:
      matrix:
        node: [22, 24]
      fail-fast: false
    uses: luxass/shared-workflows/.github/workflows/reusable-test.yaml@b55f08ac1aca5a4a3ae198bd8a7197c0157b3ef7 # v0.10.0
    with:
      node-version: ${{ matrix.node }}
