name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: generate nuxt types
        run: pnpm run --filter @unplugin-yaml/nuxt-example generate:types

      - name: lint
        run: pnpm lint

      - name: typecheck
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20, 22, 24]
      fail-fast: false
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: setup node ${{ matrix.node }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node }}

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test
