name: Release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: luxass/shared-workflows/.github/workflows/reusable-release-npm.yaml@f679de59851660fb23fd7e453ea66b9e76cb55aa # v0.11.0
    with:
      environment: npm-registry
      stage: true
