name: Release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: setup node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: lts/*

      - name: update npm (oidc)
        run: npm install -g npm@latest

      - name: generate changelog
        run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: detect tag
        id: tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)

          if [[ "$LATEST_TAG" == *-* ]]; then
            echo "tag=next" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: publish to npm
        run: pnpm publish --tag $TAG --access public --no-git-checks
        env:
          TAG: ${{ steps.tag.outputs.tag }}
          NPM_CONFIG_PROVENANCE: true

      - name: print dirty files
        run: git status --porcelain
