name: Test Build Tools

on:
  workflow_dispatch:
  schedule:
    # every sunday at 00:00
    - cron: "0 0 * * 0"

permissions: {}

jobs:
  test-build-tools:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        tool:
          # rspack
          - { name: "@rspack/core", version: latest }
          - { name: "@rspack/core", version: alpha }
          - { name: "@rspack/core", version: beta }
          - { name: "@rspack/core", version: 1.1.8 }

          # webpack
          - { name: webpack, version: latest }
          - { name: webpack, version: 5.73.0 }

          # esbuild
          - { name: esbuild, version: latest }
          - { name: esbuild, version: 0.19.12 }

          # rollup
          - { name: rollup, version: latest }
          - { name: rollup, version: beta }
          - { name: rollup, version: 4.22.5 }
          - { name: rollup, version: 4.17.0 }

          # rolldown
          - { name: rolldown, version: latest }
          - { name: rolldown, version: 1.0.0 }

          # vite
          - { name: vite, version: latest }
          - { name: vite, version: beta }
          - { name: vite, version: 8.0.0 }
          - { name: vite, version: 7.3.5 }
          - { name: vite, version: 6.4.3 }

    uses: luxass/shared-workflows/.github/workflows/reusable-test-build-tools.yaml@f679de59851660fb23fd7e453ea66b9e76cb55aa # v0.11.0
    with:
      tool-name: ${{ matrix.tool.name }}
      tool-version: ${{ matrix.tool.version }}
