name: Test Build Tools

on:
  workflow_dispatch:
  schedule:
    # every sunday at 00:00
    - cron: "0 0 * * 0"

jobs:
  test-rspack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - latest
          - alpha
          - beta
          - 1.1.8
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: setup node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: lts/*

      - name: install
        run: pnpm install --frozen-lockfile

      - name: install rspack ${{ matrix.version }}
        run: pnpm add -Dw @rspack/core@${{ matrix.version }}

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test

      - name: typecheck
        run: pnpm typecheck
