name: Test Build Tools

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-rspack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [20, 22]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        versions:
            - latest
            - alpha
            - beta
            - 1.1.8
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: setup node ${{ matrix.node }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: install
        run: pnpm install --frozen-lockfile

      - name: install rspack ${{ matrix.versions }}
        run: pnpm add -Dw @rspack/core@${{ matrix.versions }}

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test

      - name: typecheck
        run: pnpm typecheck
